### ISSUE TITLE
Support for bintray sbt plugin

### ISSUE THREAD

**Issue by gkossakowski** [typesafehub/dbuild#158] opened 2015-01-14 14:23 UTC
Projects using bintray sbt plugin cannot be built by dbuild at the moment. The problem has been originally reported as sbt/sbt-testng-interface#4. @cunei has investigated it and concluded that dbuild needs special support for bintray plugin:

> Yep. The bintray-sbt plugin, according to its source, overrides publishTo, publish, publishConfiguration, and credentials (and other stuff). Subsequently, dbuild overwrites publishTo (so that the artifacts end up in its own cache), but assumes publish will be unchanged and will actually publish to the rewritten publishTo. So this won't work, and dbuild will need to work around that, either by disabling the bintray plugin or by rewriting publish in order to set it /again/ to the default one, which will probably do the trick.

Until explicit support for bintray arrives we'll need to get rid of bintray settings by forking projects using it. See for example gkossakowski/sbt-testng-interface@41b39ec59491adfeb93b52390d62bb52afee73fc.

I set priority to medium because this issue forces us to keep forks of projects we are building around.

**Comment by SethTisue** [comment] 2016-09-28 19:03
this hasn't been causing me any trouble in the Scala community build in the past year. maybe not an issue anymore

well, with perhaps one exception: https://github.com/scala/community-builds/pull/290

**Comment by SethTisue** [comment] 2016-12-06 03:43
@cunei I'm seeing this in ScalaMock here: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1055/consoleFull, even with dbuild 0.9.7-RC1

ScalaMock is not the only project in the community build that uses bintray-sbt 0.3.0. I'm not sure what the difference is

**Comment by SethTisue** [comment] 2016-12-06 04:41
akka-http, too, at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1056/consoleFull:

```
[akka-http] Running "compile" in: akka-parsing
[akka-http] [warn] Credentials file /home/jenkins/.bintray/.credentials does not exist
[akka-http] Publishing: akka-parsing
[akka-http] bintray-sbt requires your bintray credentials.
[akka-http] Enter bintray username: java.util.NoSuchElementException: None.get
```

**Comment by SethTisue** [comment] 2016-12-10 23:18
hit this twice more recently — had to fork akka-sse and akka-contrib-extras to get around it

**Comment by SethTisue** [comment] 2017-02-10 03:28
hit this again with scalameta in https://github.com/scala/community-builds/pull/472

the bintray plugin was long unmaintained, but was recently moved to the sbt org. perhaps there's a possibility of addressing this now from the plugin's end

**Comment by dwijnand** [comment] 2017-02-22 01:28
Strictly WRT the None.get case I think it should be possible to change sbt-bintray, not by special-casing sbt-bintray in dbuild - an acceptable variant on https://github.com/sbt/sbt-bintray/pull/69 would suffice (see my comments at the end).

**Comment by SethTisue** [comment] 2017-04-24 18:43
> Strictly WRT the None.get case I think it should be possible to change sbt-bintray, not by special-casing sbt-bintray in dbuild

yeah but based on @cunei's remarks (quoted by Grzegorz at the top of this ticket), the problem is more fundamental than that, I think — working around the `None.get` would likely only expose further problems...?

this is getting to be a bigger and bigger problem for the community build, as more projects adopt Bintray — we're up to nine forked projects over this one issue. 

is there any chance you guys could give this issue a look and arrive at a fix or workaround that doesn't require forking projects? whether the fix is in dbuild or sbt-bintray or some combination...? (or are you maxed out until sbt 1.0 is out?)

**Comment by dwijnand** [comment] 2017-04-24 21:18
I've put it on my overflow list, hopefully I can carve out some time to work on it. But generally, yeah, we're all out on sbt 1 atm.

**Comment by SethTisue** [comment] 2017-08-12 04:06
I'm finding that the following combination works:

* dbuild 0.9.9
* sbt-bintray 0.5.1
* `extra.options: ["-Dbintray.user=dummy", "-Dbintray.pass=dummy"]`

@cunei so, you can close this ticket 🎉

**Closed** 2017-08-12 19:40 UTC
Labels: enhancement, Medium
